Files:
  - FileName: Performance\APRC.yaml
    Enabled: true
  - FileName: Performance\Blocking.yaml
    Enabled: true
  - FileName: Performance\CPU.yaml
    Enabled: true
  - FileName: Performance\CPU_Compilation.yaml
    Enabled: true
  - FileName: Performance\CPU_UserPoolCPUDiscrepancy.yaml
    Enabled: true
  - FileName: Performance\Dump.yaml
    Enabled: true
  - FileName: Performance\Filefull.yaml
    Enabled: true
  - FileName: Performance\Memory.yaml
    Enabled: true
  - FileName: Performance\Misc.yaml
    Enabled: true
  - FileName: Performance\Misc_DatabaseCorruption.yaml
    Enabled: true
  - FileName: Performance\MonDmCloudDatabaseWaitStats_ActionPlan.yaml
    Enabled: true
  - FileName: Performance\QDS.yaml
    Enabled: true
  - FileName: Performance\QDS_ReadonlyAnalysis_EP.yaml
    Enabled: true
  - FileName: Performance\QDS_ReadonlyAnalysis_Singleton.yaml
    Enabled: true
  - FileName: Performance\QDS_ReadonlyAnalysis_SharedSkills.yaml
    Enabled: true
  - FileName: Performance\OOD.yaml
    Enabled: true
  - FileName: Performance\queries_AntiPattern.yaml
    Enabled: true
  - FileName: Performance\queries_ComparisonOfHistoricalData.yaml
    Enabled: false
  - FileName: Performance\Queries_FailedQuerySummary.yaml
    Enabled: true
  - FileName: Performance\queries_MonDmTranActiveTransactions.yaml
    Enabled: true
  - FileName: Performance\queries_QueryDetails.yaml
    Enabled: true
  - FileName: Performance\queries_topQueries.yaml
    Enabled: true
  - FileName: Performance\queries_Wait.yaml
    Enabled: true
  - FileName: Performance\queries1.yaml
    Enabled: true
  - FileName: Performance\Query_WaitType_ActionPlans.yaml
    Enabled: true
  - FileName: Performance\SqlOS.yaml
    Enabled: true
  - FileName: Performance\sqlSkills.yaml
    Enabled: true
  - FileName: Performance\Storage_XStore.yaml
    Enabled: true
  - FileName: Performance\worker.yaml
    Enabled: true
  - FileName: Performance\Overbooking_memory.yaml
    Enabled: true
